-- Air pressure was previously generated by the demo seed even though NeuroSense
-- hardware does not report it. Remove only synthetic readings while preserving
-- the nullable legacy column for backwards-compatible ingestion.
UPDATE measurements
SET
  air_pressure = NULL,
  raw_object = raw_object #- '{sensors,pressure_sensor}'
WHERE air_pressure IS NOT NULL
  AND raw_object->>'demo' = 'true';

UPDATE nodes
SET last_sensor_presence = last_sensor_presence - 'pressure_sensor'
WHERE organization_id = 'org-neurocrop-demo'
  AND last_sensor_presence ? 'pressure_sensor';

-- Air pressure is no longer a supported NeuroCrop profile metric.
UPDATE crop_profiles
SET metrics = metrics - 'airPressure'
WHERE metrics ? 'airPressure';
