import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router'
import { useInterfaceLanguage } from '../../i18n'
import { neurocropApi } from '../../services/api/neurocropApi'
import { useDashboardState } from '../../state/dashboardStore'
import { metricDefinitions } from '../../domain/metricRegistry'
import { diagnosticErrorMessage } from './requestErrors'
import { readDiagnosticView, rememberDiagnosticView, rememberDiagnosticTab, type DiagnosticSessionView } from './sessionView'
import DiagnosticSummary from './DiagnosticSummary'
import type { DiagnosticReport, ReportListItem } from './types'
import '../../styles/diagnostics-workspace.css'

type Area={id:string;name:string;mapEnabled?:boolean;map_enabled?:boolean}
type Action={id:string;areaId:string;sectionName:string;title:string;reason:string;recommendedAction:string;priority:string}
const asList = <T,>(value:unknown,key:string):T[] => Array.isArray(value)?value:((value as Record<string,unknown>)?.[key] as T[] || [])
const number=(n:number|null|undefined,d=1)=>n==null?'—':n.toLocaleString(undefined,{maximumFractionDigits:d})

export default function DiagnosticsWorkspace(){
  const {language}=useInterfaceLanguage(),lt=language==='lt',navigate=useNavigate(),context=useDashboardState()
  const t=(a:string,b:string)=>lt?a:b
  const [areas,setAreas]=useState<Area[]>([]),[areaId,setAreaId]=useState(context.context.areaId||''),[days,setDays]=useState(7)
  const [report,setReport]=useState<DiagnosticReport|null>(null),[reports,setReports]=useState<ReportListItem[]>([])
  const [actions,setActions]=useState<Action[]>([]),[savedId,setSavedId]=useState<string|null>(null),[tab,setTab]=useState('insights')
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false)
  const [message,setMessage]=useState(''),[schedule,setSchedule]=useState(false),[canWrite,setCanWrite]=useState(false),[canConfigure,setCanConfigure]=useState(false)
  const [farms,setFarms]=useState<Area[]>([])
  const [sessionScope,setSessionScope]=useState('')
  const restoredView=useRef<DiagnosticSessionView|null>(null)
  const generation=useRef(0),analysisRequest=useRef<AbortController|null>(null)
  const metricLabel=(key:string)=>{const d=metricDefinitions[key as keyof typeof metricDefinitions];return d?(lt?d.labelLt:d.label):key}
  const date=(value:string)=>new Date(value).toLocaleString(lt?'lt-LT':'en-GB')
  useEffect(()=>{
    let active=true
    Promise.all([neurocropApi.getAreas(),neurocropApi.getCurrentUser()]).then(([a,u])=>{
      if(!active)return
      const list=asList<Area>(a,'areas'),user=(u as {user?:{id?:string;organizationId?:string;role?:string}}).user
      const scope=JSON.stringify([user?.id,user?.organizationId,user?.role])
      const previous=readDiagnosticView(scope)
      const restored=previous&&list.some(x=>x.id===previous.areaId)?previous:null
      restoredView.current=restored
      setAreas(list);setAreaId(current=>restored?.areaId||(list.some(x=>x.id===current)?current:list[0]?.id||''))
      if(restored){setDays(restored.days);setTab(restored.tab)}
      setSessionScope(scope)
      const role=user?.role||'';setCanWrite(['owner','admin','grower'].includes(role));setCanConfigure(['owner','admin','technician'].includes(role))
      if(!list.length)setLoading(false)
    }).catch(e=>{if(active){setError(String(e.message));setLoading(false)}})
    return()=>{active=false}
  },[])
  useEffect(()=>{
    if(!areaId||!sessionScope)return
    const version=++generation.current,controller=new AbortController()
    analysisRequest.current=controller
    const previous=restoredView.current
    const restored=previous&&previous.areaId===areaId&&previous.days===days?previous:null
    restoredView.current=null
    queueMicrotask(()=>{if(version===generation.current){setLoading(false);setError('');setMessage('');setReport(restored?.report??null);setSavedId(restored?.savedId??null);setActions([]);setSchedule(false)}})
    void Promise.allSettled([neurocropApi.getDiagnosticReports(),neurocropApi.getTodayActions(),neurocropApi.getDiagnosticSchedule(areaId)]).then(results=>{
      if(controller.signal.aborted)return
      const [list,a,s]=results.map(result=>result.status==='fulfilled'?result.value:{})
      setReports(asList<ReportListItem>(list,'reports'));setActions(asList<Action>(a,'actions'));setSchedule(Boolean((s as {enabled:boolean}).enabled))
      if(results.some(result=>result.status==='rejected'))setMessage('diagnostic-supplementary-error')
    })
    void neurocropApi.getDiagnosticFarms().then(f=>{if(!controller.signal.aborted)setFarms(asList<Area>(f,'farms'))}).catch(()=>{})
    return()=>{controller.abort();analysisRequest.current?.abort()}
  },[areaId,days,sessionScope])
  useEffect(()=>{if(sessionScope)rememberDiagnosticTab(sessionScope,tab)},[sessionScope,tab])
  async function generateReport(){
    if(!areaId||!sessionScope||loading)return
    analysisRequest.current?.abort()
    const controller=new AbortController(),version=++generation.current
    analysisRequest.current=controller
    setLoading(true);setError('');setMessage('');setReport(null);setSavedId(null);setTab('insights')
    try{
      const result=await neurocropApi.getAreaDiagnostics(areaId,{days},controller.signal) as DiagnosticReport
      if(controller.signal.aborted||version!==generation.current)return
      setReport(result)
      rememberDiagnosticView(sessionScope,{areaId,days,report:result,savedId:null,tab:'insights'})
    }catch(e){if(!controller.signal.aborted&&version===generation.current)setError(diagnosticErrorMessage(e))}
    finally{if(!controller.signal.aborted&&version===generation.current)setLoading(false)}
  }
  async function run(task:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await task()}catch(e){setError(diagnosticErrorMessage(e))}finally{setBusy(false)}}
  async function save(){await run(async()=>{const result=await neurocropApi.createDiagnosticReport({areaId,days,to:report?.to,timeZone:report?.timeZone}) as {id:string;snapshot:DiagnosticReport};setSavedId(result.id);setReport(result.snapshot);rememberDiagnosticView(sessionScope,{areaId,days,report:result.snapshot,savedId:result.id,tab});setReports(asList<ReportListItem>(await neurocropApi.getDiagnosticReports(),'reports'));setMessage(t('Ataskaita išsaugota. Vėlesni profilio pakeitimai jos nekeis.','Report saved. Later profile changes will not change this snapshot.'))})}
  async function openReport(id:string){analysisRequest.current?.abort();generation.current++;await run(async()=>{const r=await neurocropApi.getDiagnosticReport(id) as {id:string;snapshot:DiagnosticReport};const view:DiagnosticSessionView={areaId:r.snapshot.area.id,days:r.snapshot.days,report:r.snapshot,savedId:r.id,tab:'insights'};if(areaId!==view.areaId||days!==view.days)restoredView.current=view;setAreaId(view.areaId);setDays(view.days);setReport(r.snapshot);setSavedId(r.id);setLoading(false);setTab('insights');rememberDiagnosticView(sessionScope,view)})}
  const areaActions=actions.filter(a=>a.areaId===areaId)
  const tabs=[['insights',t('Įžvalgos','Findings')],['episodes',t('Įvykių istorija','Event history')],['reports',t('Ataskaitos','Reports')]]
  const reportLibrary = <section className={`diag-panel no-print ${tab==='reports'?'active':''}`}><h2>{t('Ataskaitų biblioteka','Report library')}</h2><p>{t('Išsaugota ataskaita nekinta keičiant profilius, zonas ar sensorių nustatymus.','Saved reports remain unchanged when profiles, zones or sensor settings change.')}</p><label className="diag-schedule no-print"><input type="checkbox" checked={schedule} disabled={!canWrite||busy} onChange={e=>{const enabled=e.target.checked;void run(async()=>{await neurocropApi.saveDiagnosticSchedule(areaId,{enabled,days,timeZone:report?.timeZone||Intl.DateTimeFormat().resolvedOptions().timeZone});setSchedule(enabled);setMessage(t('Ataskaitų periodiškumas išsaugotas.','Report schedule saved.'))})}}/>{t(`Automatiškai išsaugoti kas ${days} dienų`,`Automatically save every ${days} days`)}</label>{!reports.some(r=>r.area_id===areaId)?<div className="diag-library-empty"><i className="fa-regular fa-file-lines" aria-hidden="true"/><strong>{t('Išsaugotų ataskaitų dar nėra','No saved reports yet')}</strong><p>{t('Sugeneruokite analizę ir spauskite „Išsaugoti ataskaitą“. Čia galėsite sugrįžti prie jos vėliau.','Generate an analysis and select Save report. You can return to it here later.')}</p></div>:null}{reports.filter(r=>r.area_id===areaId).map(r=><article className="diag-report-row" key={r.id}><div><strong>{r.area.name} · {r.days} {t('dienų','days')}</strong><p>{date(r.from)} — {date(r.to)}</p></div><button disabled={busy} onClick={()=>void openReport(r.id)}>{t('Atverti','Open')}</button><button disabled={busy} onClick={()=>void run(async()=>{await neurocropApi.downloadDiagnosticCsv(r.id)})}>CSV</button></article>)}</section>
  return <div className="nc-diagnostics" data-nc-react-workspace="diagnostics">
    <header className="diag-heading"><div><span className="diag-eyebrow">{t('AUGINIMO SĄLYGŲ ANALIZĖ','GROWING CONDITIONS ANALYSIS')}</span><h1>{t('Šiltnamio diagnostika','Greenhouse diagnostics')}</h1><p>{t('Supraskite poveikį augalams. Žinokite, ką tikrinti ir ką keisti.','Understand the plant response. Know what to check and what to change.')}</p></div><div className="diag-toolbar no-print"><button disabled={!report||busy||loading} onClick={()=>window.print()}><i className="fa-solid fa-print" aria-hidden="true"/>{t('Spausdinti / PDF','Print / PDF')}</button><button className="primary" disabled={!report||busy||loading||!canWrite||Boolean(savedId)} onClick={()=>void save()}><i className={`fa-solid ${savedId?'fa-check':'fa-bookmark'}`} aria-hidden="true"/>{savedId?t('Išsaugota','Saved'):t('Išsaugoti ataskaitą','Save report')}</button></div></header>
    <section className="diag-filters no-print"><label>{t('Šiltnamis','Greenhouse')}<select value={areaId} disabled={busy} onChange={e=>{setAreaId(e.target.value);setMessage('')}}>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t('Laikotarpis','Period')}<select value={days} disabled={busy} onChange={e=>setDays(Number(e.target.value))}>{[7,14,30].map(d=><option key={d} value={d}>{d} {t('dienų','days')}</option>)}</select></label><button className="primary" disabled={busy||loading||!areaId||!sessionScope} onClick={()=>void generateReport()}>{loading?t('Generuojama…','Generating…'):t('Generuoti ataskaitą','Generate report')}</button></section>
    {error?<p className="diag-error" role="alert">{error==='diagnostic-timeout'?t('Analizė užtruko ilgiau nei tikėtasi. Bandykite dar kartą arba pasirinkite trumpesnį laikotarpį.','The analysis took longer than expected. Try again or choose a shorter period.'):error}</p>:null}{message?<p role="status" className="diag-notice">{message==='diagnostic-supplementary-error'?t('Nepavyko įkelti papildomų duomenų. Atverkite puslapį dar kartą.','Some additional data could not be loaded. Reopen this page to retry.'):message}</p>:null}
    <nav className="diag-tabs no-print" aria-label={t('Diagnostikos skiltys','Diagnostic sections')}>{tabs.map(([id,label])=><button disabled={id==='episodes'&&!report} key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}<button disabled={!report} className="diag-setup-link" aria-current={tab==='inputs'?'page':undefined} onClick={()=>setTab('inputs')}>{t('Duomenys','Data')}</button></nav>
    {loading?<section className="diag-state diag-loading" role="status" aria-live="polite"><span className="diag-state-icon"><i className="fa-solid fa-circle-notch fa-spin" aria-hidden="true"/></span><h2>{t('Rengiama jūsų šiltnamio ataskaita','Preparing your greenhouse report')}</h2><p>{t('Analizuojami matavimai. 30 dienų analizė gali užtrukti iki pusantros minutės…','Analyzing readings. A 30-day analysis may take up to a minute and a half…')}</p><div className="diag-loading-track" aria-hidden="true"><span/></div></section>:!sessionScope?<section className="diag-state" role="status"><span className="diag-state-icon"><i className="fa-solid fa-circle-notch fa-spin" aria-hidden="true"/></span><p>{t('Įkeliami šiltnamiai…','Loading greenhouses…')}</p></section>:!areas.length?<section className="diag-state"><span className="diag-state-icon"><i className="fa-solid fa-seedling" aria-hidden="true"/></span><h2>{t('Pradėkite nuo šiltnamio','Start with a greenhouse')}</h2><p>{t('Pirmiausia sukurkite šiltnamį ir priskirkite mazgus.','Create a greenhouse and assign nodes first.')}</p><button onClick={()=>navigate('/areas')}>{t('Atverti šiltnamius','Open greenhouses')}</button></section>:!report&&!error&&tab==='insights'?<section className="diag-state diag-start"><span className="diag-state-icon"><i className="fa-regular fa-file-lines" aria-hidden="true"/></span><span className="diag-eyebrow">{t('NUO MATAVIMŲ IKI SPRENDIMO','FROM READINGS TO DECISIONS')}</span><h2>{t('Ką jūsų šiltnamio sąlygos reiškia augalams?','What do your greenhouse conditions mean for plants?')}</h2><p>{t('Pasirinkite šiltnamį ir laikotarpį, tada spauskite „Generuoti ataskaitą“.','Choose a greenhouse and period, then select Generate report.')}</p><div className="diag-start-benefits"><div><i className="fa-solid fa-leaf" aria-hidden="true"/><strong>{t('Poveikis augalams','Plant response')}</strong><span>{t('Kartu vertinami klimatas, šviesa ir šaknų zona.','Climate, light and root-zone conditions assessed together.')}</span></div><div><i className="fa-solid fa-list-check" aria-hidden="true"/><strong>{t('Aiškūs veiksmai','Clear actions')}</strong><span>{t('Ką patikrinti pirmiausia ir kaip pasirinkti korekciją.','What to check first and how to choose an adjustment.')}</span></div><div><i className="fa-solid fa-chart-line" aria-hidden="true"/><strong>{t('Pagrįstos išvados','Supporting evidence')}</strong><span>{t('Matavimai, trukmės ir būdas įvertinti rezultatą.','Readings, durations and a way to assess the result.')}</span></div></div><small>{t('Įžvalgų apimtis priklauso nuo prijungtų jutiklių ir auginimo profilio.','The available sensors and crop profile determine what can be assessed.')}</small></section>:null}
    {reportLibrary}
    {report?<><div className="diag-period"><strong>{report.area.name}</strong><span title={`${date(report.from)} — ${date(report.to)} · ${report.timeZone}`}>{new Date(report.from).toLocaleDateString(lt?'lt-LT':'en-GB')} — {new Date(report.to).toLocaleDateString(lt?'lt-LT':'en-GB')}</span><b>{savedId?t('Išsaugota ataskaita','Saved snapshot'):t('Paskutinė analizė','Latest analysis')}</b></div>
      {report.warnings.includes('legacy-context-estimated')?<details className="diag-history-note"><summary>{t('Senesnių matavimų vertinimas gali būti netikslus','Older readings may be assessed less accurately')}</summary><p>{t('Dalį senesnių matavimų vertiname pagal šiandien nustatytas ribas. Jei keitėte ribas ar perkėlėte jutiklius, šio laikotarpio išvadas vertinkite atsargiai.','Older readings are compared with today’s targets. If you changed targets or moved sensors, interpret these findings with care.')}</p></details>:null}

      <section className={`diag-panel ${tab==='insights'?'active':''}`}>
        <DiagnosticSummary key={`${report.area.id}:${report.from}:${report.to}:${savedId||"current"}`} report={report} lt={lt} onCheckSensors={()=>navigate('/nodes')}/>
        {!savedId&&areaActions.length?<details className="diag-more"><summary>{t('Šiuo metu siūlomi veiksmai','Actions suggested right now')}</summary>{areaActions.map(a=><article className="diag-action" key={a.id}><strong>{a.sectionName} · {a.title}</strong><p>{a.reason}</p><p>{a.recommendedAction}</p><button className="no-print" onClick={()=>navigate('/actions')}>{t('Atverti veiksmus','Open actions')}</button></article>)}</details>:null}
      </section>
      <section className={`diag-panel ${tab==='episodes'?'active':''}`}><h2>{t('Anomalijų epizodai','Anomaly episodes')}</h2><p>{t('Įvykiai kaupiami fone nuo diagnostikos įdiegimo. Pradžia ir pabaiga remiasi matavimų laiku; duomenų tarpas užbaigia stebėjimą kaip nežinomą.','Events accumulate in the background from diagnostic installation. Start and end use observation time; a data gap ends observation as unknown.')}</p><div className="diag-table-scroll"><table><thead><tr>{[t('Vieta / rodiklis','Location / metric'),t('Tipas','Type'),t('Pradžia','Start'),t('Pabaiga','End'),t('Įrodymai','Evidence')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.episodes.map(e=><tr key={e.id}><th>{report.metrics.find(m=>m.sectionId===e.section_id)?.name||e.section_id}<small>{e.node_id} · {metricLabel(e.metric)}</small></th><td>{e.kind==='peer'?t('Skirtumas nuo kitų','Peer difference'):e.kind==='rate'?t('Staigus pokytis','Rapid change'):t('Už ribų','Outside target')}<small>{e.severity}</small></td><td>{date(e.started_at)}</td><td>{e.ended_at?date(e.ended_at):t('Tęsiasi','Ongoing')}<small>{e.resolution_reason==='data_gap'?t('Duomenų tarpas','Data gap'):e.resolution_reason}</small></td><td><details><summary>{t('Peržiūrėti','Review')}</summary><pre>{JSON.stringify(e.evidence,null,2)}</pre></details></td></tr>)}</tbody></table></div>{!report.episodes.length?<p>{t('Šiuo laikotarpiu užregistruotų epizodų nėra.','No episodes recorded in this window.')}</p>:null}</section>
      <section className={`diag-panel ${tab==='inputs'?'active':''}`}><h2>{t('Duomenų pakankamumas','Input readiness')}</h2><div className="diag-cards">{Object.entries(report.inputs).map(([key,available])=><article key={key}><strong>{({controller:t('Valdiklio įvykiai','Controller events'),calibration:t('Kalibravimas','Calibration'),cycle:t('Auginimo ciklas','Growing cycle'),ppfd:'PAR / PPFD',energy:t('Energijos sąnaudos','Energy consumption'),yield:t('Derliaus rezultatai','Yield outcomes')} as Record<string,string>)[key]}</strong><p>{available?t('Yra įrašų; tikrinkite aprėptį','Records available; verify coverage'):t('Duomenys dar neprijungti','Inputs not connected')}</p></article>)}</div><p>{t('Vien matavimų sutapimas nepatvirtina priežasties. Derliaus ir energijos nuostolių neskaičiuojame be faktinių rezultatų bei sąnaudų.','Correlation alone does not establish cause. Yield and energy losses require actual outcome and consumption data.')}</p>
        <h3>{t('Įrangos ir atliktų veiksmų įvykiai','Equipment and intervention events')}</h3>{report.controllerEvents.map(e=><p key={e.id}>{date(e.occurred_at)} · {e.device_id} · {e.channel} · {e.source==='manual'?t('Rankinis įrašas','Manual entry'):t('Valdiklio duomenys','Controller data')}</p>)}{report.interventions.map(e=><p key={e.id}>{date(e.performed_at)} · {e.action_type} · {e.note} · {e.outcome_status||t('Rezultatas dar neįvertintas','Outcome pending')}</p>)}
        <h3>{t('Zonų reakcija prieš ir po įvykio','Zone response before and after an event')}</h3><p>{t('Lyginami 30 min langai abipus įvykio. Pokytis rodomas tik turint bent 50 % abiejų langų aprėptį. Tai laikinis sutapimas, ne įrodytas įrangos poveikis; kiti tuo metu vykę veiksmai gali keisti rezultatą.','Compares 30-minute windows on either side. Delta requires at least 50% coverage in both windows. This is association, not proven equipment impact; concurrent actions may confound the result.')}</p>{report.controllerResponsesTruncated?<p>{t('Rodomi paskutiniai 100 įvykių.','Showing the latest 100 events.')}</p>:null}
        {(report.controllerResponses||[]).map(e=><details key={e.eventId}><summary>{date(e.occurredAt)} · {e.channel} · {e.source}</summary><div className="diag-table-scroll"><table><thead><tr><th>{t('Zona / rodiklis','Zone / metric')}</th><th>{t('Prieš / po','Before / after')}</th><th>Δ</th><th>{t('Aprėptis prieš / po','Coverage before / after')}</th></tr></thead><tbody>{e.zones.map(z=><tr key={`${z.sectionId}:${z.metric}`}><th>{z.name} · {metricLabel(z.metric)}</th><td>{number(z.before)} / {number(z.after)}</td><td>{number(z.delta)}</td><td>{number(z.beforeCoveragePct)} / {number(z.afterCoveragePct)} %</td></tr>)}</tbody></table></div></details>)}
        {canConfigure?<details className="no-print"><summary>{t('Registruoti įrangos veiksmą rankiniu būdu','Record equipment action manually')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await neurocropApi.createControllerEvent({areaId,source:'manual',externalId:crypto.randomUUID(),deviceId:data.deviceId,channel:data.channel,occurredAt:new Date(String(data.occurredAt)).toISOString(),state:{value:data.value,note:data.note}});setMessage(t('Įrašas išsaugotas. Norėdami įtraukti jį į analizę, spauskite „Generuoti ataskaitą“.','Record saved. Select Generate report to include it in the analysis.'))})}}><label>{t('Įranga','Equipment')}<input name="deviceId" required maxLength={200}/></label><label>{t('Veiksmas / kanalas','Action / channel')}<input name="channel" required maxLength={200}/></label><label>{t('Būsena','State')}<input name="value" required maxLength={200}/></label><label>{t('Laikas','Time')}<input name="occurredAt" type="datetime-local" required/></label><label>{t('Pastaba','Note')}<input name="note" maxLength={1000}/></label><button disabled={busy}>{t('Registruoti','Record')}</button></form></details>:null}
        {canWrite?<details className="no-print"><summary>{t('Ūkio ir šiltnamio struktūra','Farm and greenhouse structure')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name'));void run(async()=>{await neurocropApi.createDiagnosticFarm({name});setFarms(asList<Area>(await neurocropApi.getDiagnosticFarms(),'farms'))})}}><label>{t('Naujo ūkio pavadinimas','New farm name')}<input name="name" required maxLength={200}/></label><button disabled={busy}>{t('Sukurti ūkį','Create farm')}</button></form><label>{t('Priskirti šiltnamį ūkiui','Assign greenhouse to farm')}<select defaultValue="" disabled={busy} onChange={e=>void run(async()=>{await neurocropApi.assignDiagnosticFarm(areaId,e.target.value);setMessage(t('Ūkis priskirtas.','Farm assigned.'))})}><option value="">—</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></details>:null}
        {canWrite?<details className="no-print"><summary>{t('Pridėti auginimo ciklą','Add growing cycle')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run(async()=>{await neurocropApi.createDiagnosticCycle(Object.fromEntries(data));setMessage(t('Įrašas išsaugotas. Norėdami įtraukti jį į analizę, spauskite „Generuoti ataskaitą“.','Record saved. Select Generate report to include it in the analysis.'))})}}><label>{t('Zona','Section')}<select name="sectionId">{Array.from(new Map(report.metrics.map(m=>[m.sectionId,m.name]))).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>{t('Kultūra','Crop')}<input name="crop" required/></label><label>{t('Stadija','Stage')}<input name="stage"/></label><label>{t('Partija','Batch')}<input name="batchId"/></label><label>{t('Eksperimentas','Experiment')}<input name="experimentId"/></label><label>{t('Pradžia','Start')}<input name="startsAt" type="date" required/></label><label>{t('Pabaiga','End')}<input name="endsAt" type="date"/></label><button disabled={busy}>{t('Išsaugoti','Save')}</button></form></details>:null}
        {canConfigure?<details className="no-print"><summary>{t('Registruoti sensoriaus kalibravimą','Record sensor calibration')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await neurocropApi.createDiagnosticCalibration({...data,uncertainty:data.uncertainty?Number(data.uncertainty):null});setMessage(t('Įrašas išsaugotas. Norėdami įtraukti jį į analizę, spauskite „Generuoti ataskaitą“.','Record saved. Select Generate report to include it in the analysis.'))})}}><label>{t('Mazgas','Node')}<select name="nodeId">{Array.from(new Map(report.nodes.map(n=>[n.nodeId,n.nodeName]))).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>{t('Sensorius / kanalas','Sensor / channel')}<input name="port" placeholder="sht45" required/></label><label>{t('Etalonas ir metodas','Reference and method')}<input name="reference" required/></label><label>{t('Data','Date')}<input name="calibratedAt" type="date" required/></label><label>{t('Galioja iki','Expires')}<input name="expiresAt" type="date"/></label><label>{t('Paklaida (sensoriaus vienetais)','Uncertainty (sensor units)')}<input name="uncertainty" type="number" min="0" step="any"/></label><button disabled={busy}>{t('Išsaugoti','Save')}</button></form></details>:null}
      </section>
      <section className="diag-print-summary"><h2>{t('Visų rodiklių suvestinė','All metrics summary')}</h2><table><thead><tr><th>{t('Zona / rodiklis','Zone / metric')}</th><th>Min / Mean / Max</th><th>{t('Už ribų','Outside target')}</th><th>{t('Aprėptis','Coverage')}</th><th>Δ</th></tr></thead><tbody>{report.metrics.map(m=><tr key={`${m.sectionId}:${m.metric}`}><th>{m.name} · {metricLabel(m.metric)}</th><td>{number(m.minimum)} / {number(m.mean)} / {number(m.maximum)} {m.unit}</td><td>{number(m.outsideObservedPct)} %</td><td>{number(m.coveragePct)} %</td><td>{number(m.peerDelta)} {m.unit}</td></tr>)}</tbody></table></section>
      <details className="diag-method"><summary>{t('Kaip gaunamos šios išvados?','How are these conclusions calculated?')}</summary><p>{t('Matuojama: T, RH, CO₂, lux ir įdiegti papildomi sensoriai. Apskaičiuojama: oro VPD, laiku svertiniai vidurkiai ir skirtumai. Tarp matavimų reikšmė galioja ribotą laiką; likęs tarpas laikomas nežinomu.','Measured: T, RH, CO₂, lux and installed probes. Derived: air VPD, time-weighted means and differences. Readings are held for a bounded interval; remaining gaps are unknown.')}</p><p>{t('Zonų skirtumai lyginami sutampančiuose 5 min languose. Reitingui reikia bent 50 % aprėpties. Vienodumas ir tinkamumas augalui yra skirtingi rodikliai.','Peer differences use overlapping 5-minute windows. Ranking requires at least 50% coverage. Uniformity and crop suitability are separate metrics.')}</p><p>{t('Aprėpties vardiklis konservatyvus: kiekvienam stebėtam mazgo priskyrimui skiriamas visas laikotarpis. Perkėlus mazgą, senos ir naujos zonos aprėptis gali būti sumažinta. Kontekstas fiksuojamas gavus matavimą; pavėluotiems paketams ankstesnė konfigūracija neatkuriama.','Coverage uses the full window for every observed node assignment. Moving a node can reduce coverage in both zones. Context is captured on receipt; earlier configuration is not reconstructed for delayed packets.')}</p><small>{report.methodVersion} · {t('Sugeneruota','Generated')} {date(report.generatedAt)}</small></details>
    </>:null}
  </div>
}
