import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router'
import { useInterfaceLanguage } from '../../i18n'
import { neurocropApi } from '../../services/api/neurocropApi'
import { useDashboardState } from '../../state/dashboardStore'
import { metricDefinitions } from '../../domain/metricRegistry'
import ReadingsClimateMap from '../readings/ReadingsClimateMap'
import type { DiagnosticMetric, DiagnosticReport, ReportListItem } from './types'
import '../../styles/diagnostics-workspace.css'

type Area={id:string;name:string;mapEnabled?:boolean;map_enabled?:boolean}
type Action={id:string;areaId:string;sectionName:string;title:string;reason:string;recommendedAction:string;priority:string}
const asList = <T,>(value:unknown,key:string):T[] => Array.isArray(value)?value:((value as Record<string,unknown>)?.[key] as T[] || [])
const number=(n:number|null|undefined,d=1)=>n==null?'—':n.toLocaleString(undefined,{maximumFractionDigits:d})
const hours=(minutes:number)=>number(minutes/60)

export default function DiagnosticsWorkspace(){
  const {language}=useInterfaceLanguage(),lt=language==='lt',navigate=useNavigate(),context=useDashboardState()
  const t=(a:string,b:string)=>lt?a:b
  const [areas,setAreas]=useState<Area[]>([]),[areaId,setAreaId]=useState(context.context.areaId||''),[days,setDays]=useState(7)
  const [report,setReport]=useState<DiagnosticReport|null>(null),[reports,setReports]=useState<ReportListItem[]>([])
  const [actions,setActions]=useState<Action[]>([]),[savedId,setSavedId]=useState<string|null>(null),[tab,setTab]=useState('insights')
  const [metric,setMetric]=useState('airTemp'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true)
  const [refresh,setRefresh]=useState(0),[message,setMessage]=useState(''),[schedule,setSchedule]=useState(false),[canWrite,setCanWrite]=useState(false),[canConfigure,setCanConfigure]=useState(false)
  const [comparison,setComparison]=useState<{area:Area;metrics:DiagnosticMetric[]}[]>([])
  const [farms,setFarms]=useState<Area[]>([])
  const generation=useRef(0)
  const metricLabel=(key:string)=>{const d=metricDefinitions[key as keyof typeof metricDefinitions];return d?(lt?d.labelLt:d.label):key}
  const date=(value:string)=>new Date(value).toLocaleString(lt?'lt-LT':'en-GB')
  useEffect(()=>{
    let active=true
    Promise.all([neurocropApi.getAreas(),neurocropApi.getCurrentUser()]).then(([a,u])=>{
      if(!active)return
      const list=asList<Area>(a,'areas');setAreas(list);setAreaId(current=>list.some(x=>x.id===current)?current:list[0]?.id||'')
      const role=(u as {user?:{role?:string}}).user?.role||'';setCanWrite(['owner','admin','grower'].includes(role));setCanConfigure(['owner','admin','technician'].includes(role))
      if(!list.length)setLoading(false)
    }).catch(e=>{if(active){setError(String(e.message));setLoading(false)}})
    return()=>{active=false}
  },[])
  useEffect(()=>{
    if(!areaId)return
    const version=++generation.current
    queueMicrotask(()=>{if(version===generation.current){setLoading(true);setError('');setReport(null);setSavedId(null)}})
    Promise.allSettled([neurocropApi.getAreaDiagnostics(areaId,{days}),neurocropApi.getDiagnosticReports(),neurocropApi.getTodayActions(),neurocropApi.getDiagnosticSchedule(areaId)]).then(results=>{
      if(results[0].status==='rejected')throw results[0].reason
      const [r,list,a,s]=results.map(result=>result.status==='fulfilled'?result.value:{})
      if(results.some(result=>result.status==='rejected'))setError('Some supplementary data could not be loaded. Refresh to retry.')
      if(version!==generation.current)return
      setReport(r as DiagnosticReport);setReports(asList<ReportListItem>(list,'reports'));setActions(asList<Action>(a,'actions'));setSchedule(Boolean((s as {enabled:boolean}).enabled));setComparison([])
      void neurocropApi.getDiagnosticFarms().then(f=>{if(version===generation.current)setFarms(asList<Area>(f,'farms'))}).catch(()=>{})
    }).catch(e=>{if(version===generation.current)setError(e.message)}).finally(()=>{if(version===generation.current)setLoading(false)})
    return()=>{if(generation.current===version)generation.current=version+1}
  },[areaId,days,refresh])
  async function run(task:()=>Promise<void>){setBusy(true);setError('');setMessage('');try{await task()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function save(){await run(async()=>{const result=await neurocropApi.createDiagnosticReport({areaId,days,to:report?.to,timeZone:report?.timeZone}) as {id:string;snapshot:DiagnosticReport};setSavedId(result.id);setReport(result.snapshot);setReports(asList<ReportListItem>(await neurocropApi.getDiagnosticReports(),'reports'));setMessage(t('Ataskaita išsaugota. Vėlesni profilio pakeitimai jos nekeis.','Report saved. Later profile changes will not change this snapshot.'))})}
  async function openReport(id:string){generation.current++;await run(async()=>{const r=await neurocropApi.getDiagnosticReport(id) as {id:string;snapshot:DiagnosticReport};setReport(r.snapshot);setSavedId(r.id);setLoading(false);setTab('insights')})}
  const selected=report?.metrics.filter(m=>m.metric===metric)||[],areaActions=actions.filter(a=>a.areaId===areaId)
  const coverage=selected.length?selected.reduce((s,m)=>s+m.coveragePct,0)/selected.length:null
  const topZones=report?Array.from(new Map(report.ranking.map(m=>[m.sectionId,report.ranking.find(x=>x.sectionId===m.sectionId)!])).values()).slice(0,3):[]
  const tabs=[['insights',t('Įžvalgos ir išvados','Insights & conclusions')],['analysis',t('Zonos ir rodikliai','Zones & metrics')],['episodes',t('Anomalijų istorija','Anomaly history')],['reports',t('Ataskaitos','Reports')],['inputs',t('Duomenys ir integracijos','Data & integrations')]]
  function conclusion(m:DiagnosticMetric&{kind?:string}){
    if(m.kind==='insufficient-data')return t(`Duomenų aprėptis ${number(m.coveragePct)} %. Patikimai išvadai duomenų nepakanka.`,`Data coverage is ${number(m.coveragePct)}%. Insufficient evidence for a reliable conclusion.`)
    if(m.kind==='systematic-peer')return t(`Skirtumas nuo kitų zonų medianos ${number(m.peerDelta)} ${m.unit}; pasikartojo ${m.recurringDays} dienas.`,`Difference from peer-zone median: ${number(m.peerDelta)} ${m.unit}; recurred on ${m.recurringDays} days.`)
    return t(`Už tikslinių ribų ${number(m.outsideObservedPct)} % stebėto mazgų laiko (${hours(m.belowMinutes+m.aboveMinutes)} h).`,`Outside target for ${number(m.outsideObservedPct)}% of observed node-time (${hours(m.belowMinutes+m.aboveMinutes)} h).`)
  }
  return <div className="nc-diagnostics" data-nc-react-workspace="diagnostics">
    <header className="diag-heading"><div><p>NeuroSense</p><h1>{t('Šiltnamio diagnostika','Greenhouse diagnostics')}</h1><span>{t('Kur sąlygos skiriasi, kas kartojasi ir ką verta patikrinti.','Where conditions differ, what keeps recurring, and what to inspect.')}</span></div><div className="diag-toolbar no-print"><button onClick={()=>navigate('/nodes')}>{t('Mazgų būklė','Node health')}</button><button disabled={!report||busy||loading} onClick={()=>window.print()}>{t('Spausdinti / PDF','Print / PDF')}</button><button className="primary" disabled={!report||busy||loading||!canWrite||Boolean(savedId)} onClick={()=>void save()}>{t('Išsaugoti ataskaitą','Save report')}</button></div></header>
    <section className="diag-filters no-print"><label>{t('Šiltnamis','Greenhouse')}<select value={areaId} disabled={busy} onChange={e=>{setAreaId(e.target.value);setMessage('')}}>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t('Laikotarpis','Period')}<select value={days} disabled={busy} onChange={e=>setDays(Number(e.target.value))}>{[7,14,30].map(d=><option key={d} value={d}>{d} {t('dienų','days')}</option>)}</select></label><label>{t('Rodiklis','Metric')}<select value={metric} onChange={e=>setMetric(e.target.value)}>{['airTemp','humidity','vpd','co2','lux','soilTemp','soilMoisture','ec','ph','soilEc','leafTemp','waterTemp','ppfd'].map(m=><option key={m} value={m}>{metricLabel(m)}</option>)}</select></label><button disabled={busy||loading} onClick={()=>setRefresh(v=>v+1)}>{t('Atnaujinti','Refresh')}</button></section>
    {error?<p className="diag-error" role="alert">{error}</p>:null}{message?<p role="status" className="diag-notice">{message}</p>:null}
    {loading?<p role="status">{t('Analizuojami matavimai…','Analyzing observations…')}</p>:!areas.length?<p>{t('Pirmiausia sukurkite šiltnamį ir priskirkite mazgus.','Create a greenhouse and assign nodes first.')}</p>:null}
    {report?<><div className="diag-period"><strong>{report.area.name}</strong><span>{date(report.from)} — {date(report.to)} · {report.timeZone}</span><b>{savedId?t('Išsaugota ataskaita','Saved snapshot'):t('Dabartinė analizė','Current analysis')}</b></div>
      <div className="diag-kpis"><article><span>{t('Duomenų aprėptis','Data coverage')}</span><strong>{number(coverage)} %</strong><small>{metricLabel(metric)}</small></article><article><span>{t('Įžvalgų','Insights')}</span><strong>{report.insights.filter(i=>i.kind!=='insufficient-data').length}</strong><small>{t('Įskaitant pasikartojančius skirtumus','Including recurring differences')}</small></article><article><span>{t('Anomalijų epizodų','Anomaly episodes')}</span><strong>{report.episodes.length}{report.episodesTruncated?'+':''}</strong><small>{t('Atskiri įvykiai, ne pranešimų paspaudimai','Separate events, not notification clicks')}</small></article></div>
      {report.warnings.includes('legacy-context-estimated')?<p className="diag-notice">{t('Dalis istorijos yra iš laikotarpio prieš konteksto išsaugojimą. Šių matavimų zonos ir ribos įvertintos pagal dabartinę konfigūraciją; tai pažymėta rodiklių lentelėje.','Some observations predate context capture. Their assignments and targets are estimated from current configuration and marked in the metric table.')}</p>:null}
      <nav className="diag-tabs no-print" aria-label={t('Diagnostikos skiltys','Diagnostic sections')}>{tabs.map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}>{label}</button>)}</nav>
      <section className={`diag-panel ${tab==='insights'?'active':''}`}>
        <h2>{t('Svarbiausios vietos','Priority locations')}</h2><div className="diag-cards">{topZones.map(m=><article key={m.sectionId}><p>{m.name} · {metricLabel(m.metric)}</p><h3>{number(m.outsideObservedPct)} % {t('už ribų','outside target')}</h3><p>{conclusion(m)}</p><small>{t('Aprėptis','Coverage')}: {number(m.coveragePct)} %</small><button className="no-print" onClick={()=>{setMetric(m.metric);setTab('analysis')}}>{t('Peržiūrėti įrodymus','Review evidence')}</button></article>)}</div>
        {!topZones.length?<p>{t('Pakankamai duomenų turinčių probleminių zonų reitingui dar nėra. Tuščias sąrašas nereiškia, kad visos sąlygos tinkamos.','There is not enough evidence to rank problem zones. An empty list does not mean every condition is optimal.')}</p>:null}
        <h2>{t('Visos įžvalgos ir išvados','All insights and conclusions')}</h2><div className="diag-insights">{report.insights.map((m,i)=><article key={`${m.sectionId}-${m.metric}-${m.kind}-${i}`} data-severity={m.severity}><div><strong>{m.name} · {metricLabel(m.metric)}</strong><p>{conclusion(m)}</p><p>{m.recommendation ? (lt ? m.recommendation.lt : m.recommendation.en) : ''}</p><small>{t('Aprėptis','Coverage')}: {number(m.coveragePct)} % · {t('Palyginimo laikas','Peer comparison time')}: {hours(m.peerMinutes)} h</small></div><button className="no-print" onClick={()=>{setMetric(m.metric);setTab('analysis')}}>{t('Įrodymai','Evidence')}</button></article>)}</div>
        <h2>{t('Rekomenduojamos patikros dabar','Recommended checks now')}</h2>{savedId?<p>{t('Dabartinės rekomendacijos nėra išsaugotos ataskaitos dalis.','Current recommendations are not part of this saved report.')}</p>:areaActions.map(a=><article className="diag-action" key={a.id}><strong>{a.sectionName} · {a.title}</strong><p>{a.reason}</p><p>{a.recommendedAction}</p><button className="no-print" onClick={()=>navigate('/actions')}>{t('Atverti veiksmus','Open actions')}</button></article>)}
        {!savedId&&areas.find(a=>a.id===areaId)?.mapEnabled?<div className="no-print"><h2>{t('Dabartinis klimato žemėlapis','Current climate map')}</h2><p>{t('Žemėlapis rodo dabartinius matavimus. Aukščiau pateiktos išvados apima pasirinktą laikotarpį.','The map shows live observations. The conclusions above cover the selected period.')}</p><ReadingsClimateMap areaId={areaId} refreshToken={refresh}/></div>:null}
      </section>
      <section className={`diag-panel ${tab==='analysis'?'active':''}`}><h2>{metricLabel(metric)} · {t('zonų palyginimas','zone comparison')}</h2><p>{t('Procentai ir trukmė skaičiuojami iš mazgų stebėjimo laiko. Duomenų tarpai nėra laikomi normaliomis sąlygomis.','Percentages and durations use observed node-time. Gaps are never counted as normal conditions.')}</p><div className="diag-table-scroll"><table><thead><tr>{[t('Zona','Zone'),'Min / Mean / Max',t('Žemiau / aukščiau','Below / above'),t('Nežinoma','Unknown'),t('Aprėptis','Coverage'),t('Δ nuo kitų zonų','Peer Δ'),t('Nevienodumas','Spread'),t('Įvertintas kontekstas','Estimated context')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{selected.map(m=><tr key={m.sectionId}><th>{m.name}</th><td>{number(m.minimum)} / {number(m.mean)} / {number(m.maximum)} {m.unit}</td><td>{hours(m.belowMinutes)} / {hours(m.aboveMinutes)} h</td><td>{hours(m.unknownMinutes)} h</td><td>{number(m.coveragePct)} %</td><td>{number(m.peerDelta)} {m.unit}<small>{m.recurringDays} {t('dienos','days')}</small></td><td>{number(m.medianSpread)} / {number(m.maxSpread)} {m.unit}<small>{t('tipinis / didžiausias','median / maximum')}</small></td><td>{number(m.estimatedContextPct)} %</td></tr>)}</tbody></table></div>
        {areas.length>1?<div className="no-print"><button disabled={busy} onClick={()=>void run(async()=>{const result=await neurocropApi.getDiagnosticComparison({areaIds:areas.slice(0,6).map(a=>a.id).join(','),days,to:report.to,timeZone:report.timeZone}) as {areas:{area:Area;metrics:DiagnosticMetric[]}[]};setComparison(result.areas)})}>{t('Palyginti šiltnamius (iki 6)','Compare greenhouses (up to 6)')}</button></div>:null}
        {comparison.length?<div className="diag-table-scroll"><table><thead><tr><th>{t('Šiltnamis / zona','Greenhouse / zone')}</th><th>{t('Vidurkis','Mean')}</th><th>{t('Už savo profilio ribų','Outside own profile targets')}</th><th>{t('Aprėptis','Coverage')}</th></tr></thead><tbody>{comparison.flatMap(c=>c.metrics.filter(m=>m.metric===metric).map(m=><tr key={`${c.area.id}:${m.sectionId}`}><th>{c.area.name} / {m.name}</th><td>{number(m.mean)} {m.unit}</td><td>{number(m.outsideObservedPct)} %</td><td>{number(m.coveragePct)} %</td></tr>))}</tbody></table></div>:null}
        <h3>{t('Diena, naktis ir kaupimas','Day, night and accumulation')}</h3><div className="diag-cards">{selected.map(m=><article key={m.sectionId}><strong>{m.name}</strong><p>{t('Dienos / nakties vidurkis','Day / night mean')}: {number(m.dayMean)} / {number(m.nightMean)} {m.unit}</p>{metric==='co2'?<p>{t('CO₂ šviesos fazėje','Daylight CO₂ exposure')}: {number(m.daylightExposurePpmHours)} ppm·h ({t('mazgų suma','sum across nodes')})</p>:null}{metric==='lux'?<p>{number(m.lightAccumulationLuxHours)} lx·h ({t('mazgų suma','sum across nodes')}) · {t('tai nėra išmatuotas DLI','this is not measured DLI')}</p>:null}<small>{t('Diena ir naktis pagal tuo metu galiojusį profilio apšvietimo grafiką.','Day and night follow the observation’s profile lighting schedule.')}</small></article>)}</div>
        <h3>{t('Kada problema kartojasi','When problems recur')}</h3>{selected.map(m=><div className="diag-hour-row" key={m.sectionId}><strong>{m.name}</strong><div className="diag-hours">{m.hourly.map(h=><span key={h.hour} data-level={!h.observedMinutes?'unknown':h.outsideMinutes/h.observedMinutes>.3?'high':h.outsideMinutes?'medium':'normal'} title={`${h.hour}:00 · ${hours(h.outsideMinutes)} h · ${h.recurringDays} ${t('dienos','days')}`}><b>{h.hour}</b><small>{h.observedMinutes?`${number(100*h.outsideMinutes/h.observedMinutes,0)}%`:'—'}</small></span>)}</div></div>)}
        <h3>{t('Dienos minimumas, maksimumas ir DLI','Daily extremes and DLI')}</h3><div className="diag-table-scroll"><table><thead><tr><th>{t('Diena / mazgas','Day / node')}</th><th>Min / Mean / Max</th><th>{t('Aprėptis','Coverage')}</th><th>DLI</th></tr></thead><tbody>{report.daily?.filter(d=>d.metric===metric).map(d=><tr key={`${d.day}:${d.nodeId}:${d.sectionId}`}><th>{d.day}<small>{d.nodeName}</small></th><td>{number(d.minimum)} / {number(d.mean)} / {number(d.maximum)}</td><td>{number(d.coveragePct)} %{!d.completeCalendarDay?<small>{t('Nepilna kalendorinė diena','Partial calendar day')}</small>:null}</td><td>{d.dliObserved===null?'—':`${number(d.dliObserved)} mol/m²`}<small>{d.dliObserved!==null?t('Integruota tik stebėtu laiku','Integrated over observed time only'):''}</small></td></tr>)}</tbody></table></div>
        <h3>{t('Mazgų įrodymai' ,'Node evidence')}</h3><div className="diag-table-scroll"><table><thead><tr><th>{t('Mazgas','Node')}</th><th>{t('Zona','Zone')}</th><th>Min / Mean / Max</th><th>{t('Už ribų','Outside target')}</th><th>{t('Aprėptis','Coverage')}</th></tr></thead><tbody>{report.nodes.filter(n=>n.metric===metric).map(n=><tr key={`${n.nodeId}:${n.sectionId}`}><th>{n.nodeName}</th><td>{n.name}</td><td>{number(n.minimum)} / {number(n.mean)} / {number(n.maximum)} {n.unit}</td><td>{number(n.outsideObservedPct)} %</td><td>{number(n.coveragePct)} %</td></tr>)}</tbody></table></div>
      </section>
      <section className={`diag-panel ${tab==='episodes'?'active':''}`}><h2>{t('Anomalijų epizodai','Anomaly episodes')}</h2><p>{t('Įvykiai kaupiami fone nuo diagnostikos įdiegimo. Pradžia ir pabaiga remiasi matavimų laiku; duomenų tarpas užbaigia stebėjimą kaip nežinomą.','Events accumulate in the background from diagnostic installation. Start and end use observation time; a data gap ends observation as unknown.')}</p><div className="diag-table-scroll"><table><thead><tr>{[t('Vieta / rodiklis','Location / metric'),t('Tipas','Type'),t('Pradžia','Start'),t('Pabaiga','End'),t('Įrodymai','Evidence')].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.episodes.map(e=><tr key={e.id}><th>{report.metrics.find(m=>m.sectionId===e.section_id)?.name||e.section_id}<small>{e.node_id} · {metricLabel(e.metric)}</small></th><td>{e.kind==='peer'?t('Skirtumas nuo kitų','Peer difference'):e.kind==='rate'?t('Staigus pokytis','Rapid change'):t('Už ribų','Outside target')}<small>{e.severity}</small></td><td>{date(e.started_at)}</td><td>{e.ended_at?date(e.ended_at):t('Tęsiasi','Ongoing')}<small>{e.resolution_reason==='data_gap'?t('Duomenų tarpas','Data gap'):e.resolution_reason}</small></td><td><details><summary>{t('Peržiūrėti','Review')}</summary><pre>{JSON.stringify(e.evidence,null,2)}</pre></details></td></tr>)}</tbody></table></div>{!report.episodes.length?<p>{t('Šiuo laikotarpiu užregistruotų epizodų nėra.','No episodes recorded in this window.')}</p>:null}</section>
      <section className={`diag-panel no-print ${tab==='reports'?'active':''}`}><h2>{t('Ataskaitų biblioteka','Report library')}</h2><p>{t('Išsaugota ataskaita nekinta keičiant profilius, zonas ar sensorių nustatymus.','Saved reports remain unchanged when profiles, zones or sensor settings change.')}</p><label className="diag-schedule no-print"><input type="checkbox" checked={schedule} disabled={!canWrite||busy} onChange={e=>{const enabled=e.target.checked;void run(async()=>{await neurocropApi.saveDiagnosticSchedule(areaId,{enabled,days,timeZone:report.timeZone});setSchedule(enabled);setMessage(t('Ataskaitų periodiškumas išsaugotas.','Report schedule saved.'))})}}/>{t(`Automatiškai išsaugoti kas ${days} dienų`,`Automatically save every ${days} days`)}</label>{reports.filter(r=>r.area_id===areaId).map(r=><article className="diag-report-row" key={r.id}><div><strong>{r.area.name} · {r.days} {t('dienų','days')}</strong><p>{date(r.from)} — {date(r.to)}</p></div><button disabled={busy} onClick={()=>void openReport(r.id)}>{t('Atverti','Open')}</button><button disabled={busy} onClick={()=>void run(async()=>{await neurocropApi.downloadDiagnosticCsv(r.id)})}>CSV</button></article>)}</section>
      <section className={`diag-panel ${tab==='inputs'?'active':''}`}><h2>{t('Duomenų pakankamumas','Input readiness')}</h2><div className="diag-cards">{Object.entries(report.inputs).map(([key,available])=><article key={key}><strong>{({controller:t('Valdiklio įvykiai','Controller events'),calibration:t('Kalibravimas','Calibration'),cycle:t('Auginimo ciklas','Growing cycle'),ppfd:'PAR / PPFD',energy:t('Energijos sąnaudos','Energy consumption'),yield:t('Derliaus rezultatai','Yield outcomes')} as Record<string,string>)[key]}</strong><p>{available?t('Yra įrašų; tikrinkite aprėptį','Records available; verify coverage'):t('Duomenys dar neprijungti','Inputs not connected')}</p></article>)}</div><p>{t('Vien matavimų sutapimas nepatvirtina priežasties. Derliaus ir energijos nuostolių neskaičiuojame be faktinių rezultatų bei sąnaudų.','Correlation alone does not establish cause. Yield and energy losses require actual outcome and consumption data.')}</p>
        <h3>{t('Įrangos ir atliktų veiksmų įvykiai','Equipment and intervention events')}</h3>{report.controllerEvents.map(e=><p key={e.id}>{date(e.occurred_at)} · {e.device_id} · {e.channel} · {e.source==='manual'?t('Rankinis įrašas','Manual entry'):t('Valdiklio duomenys','Controller data')}</p>)}{report.interventions.map(e=><p key={e.id}>{date(e.performed_at)} · {e.action_type} · {e.note} · {e.outcome_status||t('Rezultatas dar neįvertintas','Outcome pending')}</p>)}
        <h3>{t('Zonų reakcija prieš ir po įvykio','Zone response before and after an event')}</h3><p>{t('Lyginami 30 min langai abipus įvykio. Pokytis rodomas tik turint bent 50 % abiejų langų aprėptį. Tai laikinis sutapimas, ne įrodytas įrangos poveikis; kiti tuo metu vykę veiksmai gali keisti rezultatą.','Compares 30-minute windows on either side. Delta requires at least 50% coverage in both windows. This is association, not proven equipment impact; concurrent actions may confound the result.')}</p>{report.controllerResponsesTruncated?<p>{t('Rodomi paskutiniai 100 įvykių.','Showing the latest 100 events.')}</p>:null}
        {(report.controllerResponses||[]).map(e=><details key={e.eventId}><summary>{date(e.occurredAt)} · {e.channel} · {e.source}</summary><div className="diag-table-scroll"><table><thead><tr><th>{t('Zona / rodiklis','Zone / metric')}</th><th>{t('Prieš / po','Before / after')}</th><th>Δ</th><th>{t('Aprėptis prieš / po','Coverage before / after')}</th></tr></thead><tbody>{e.zones.map(z=><tr key={`${z.sectionId}:${z.metric}`}><th>{z.name} · {metricLabel(z.metric)}</th><td>{number(z.before)} / {number(z.after)}</td><td>{number(z.delta)}</td><td>{number(z.beforeCoveragePct)} / {number(z.afterCoveragePct)} %</td></tr>)}</tbody></table></div></details>)}
        {canConfigure?<details className="no-print"><summary>{t('Registruoti įrangos veiksmą rankiniu būdu','Record equipment action manually')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await neurocropApi.createControllerEvent({areaId,source:'manual',externalId:crypto.randomUUID(),deviceId:data.deviceId,channel:data.channel,occurredAt:new Date(String(data.occurredAt)).toISOString(),state:{value:data.value,note:data.note}});setRefresh(v=>v+1)})}}><label>{t('Įranga','Equipment')}<input name="deviceId" required maxLength={200}/></label><label>{t('Veiksmas / kanalas','Action / channel')}<input name="channel" required maxLength={200}/></label><label>{t('Būsena','State')}<input name="value" required maxLength={200}/></label><label>{t('Laikas','Time')}<input name="occurredAt" type="datetime-local" required/></label><label>{t('Pastaba','Note')}<input name="note" maxLength={1000}/></label><button disabled={busy}>{t('Registruoti','Record')}</button></form></details>:null}
        {canWrite?<details className="no-print"><summary>{t('Ūkio ir šiltnamio struktūra','Farm and greenhouse structure')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const name=String(new FormData(e.currentTarget).get('name'));void run(async()=>{await neurocropApi.createDiagnosticFarm({name});setFarms(asList<Area>(await neurocropApi.getDiagnosticFarms(),'farms'))})}}><label>{t('Naujo ūkio pavadinimas','New farm name')}<input name="name" required maxLength={200}/></label><button disabled={busy}>{t('Sukurti ūkį','Create farm')}</button></form><label>{t('Priskirti šiltnamį ūkiui','Assign greenhouse to farm')}<select defaultValue="" disabled={busy} onChange={e=>void run(async()=>{await neurocropApi.assignDiagnosticFarm(areaId,e.target.value);setMessage(t('Ūkis priskirtas.','Farm assigned.'))})}><option value="">—</option>{farms.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label></details>:null}
        {canWrite?<details className="no-print"><summary>{t('Pridėti auginimo ciklą','Add growing cycle')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);void run(async()=>{await neurocropApi.createDiagnosticCycle(Object.fromEntries(data));setRefresh(v=>v+1)})}}><label>{t('Zona','Section')}<select name="sectionId">{Array.from(new Map(report.metrics.map(m=>[m.sectionId,m.name]))).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>{t('Kultūra','Crop')}<input name="crop" required/></label><label>{t('Stadija','Stage')}<input name="stage"/></label><label>{t('Partija','Batch')}<input name="batchId"/></label><label>{t('Eksperimentas','Experiment')}<input name="experimentId"/></label><label>{t('Pradžia','Start')}<input name="startsAt" type="date" required/></label><label>{t('Pabaiga','End')}<input name="endsAt" type="date"/></label><button disabled={busy}>{t('Išsaugoti','Save')}</button></form></details>:null}
        {canConfigure?<details className="no-print"><summary>{t('Registruoti sensoriaus kalibravimą','Record sensor calibration')}</summary><form className="diag-form" onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));void run(async()=>{await neurocropApi.createDiagnosticCalibration({...data,uncertainty:data.uncertainty?Number(data.uncertainty):null});setRefresh(v=>v+1)})}}><label>{t('Mazgas','Node')}<select name="nodeId">{Array.from(new Map(report.nodes.map(n=>[n.nodeId,n.nodeName]))).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>{t('Sensorius / kanalas','Sensor / channel')}<input name="port" placeholder="sht45" required/></label><label>{t('Etalonas ir metodas','Reference and method')}<input name="reference" required/></label><label>{t('Data','Date')}<input name="calibratedAt" type="date" required/></label><label>{t('Galioja iki','Expires')}<input name="expiresAt" type="date"/></label><label>{t('Paklaida (sensoriaus vienetais)','Uncertainty (sensor units)')}<input name="uncertainty" type="number" min="0" step="any"/></label><button disabled={busy}>{t('Išsaugoti','Save')}</button></form></details>:null}
      </section>
      <section className="diag-print-summary"><h2>{t('Visų rodiklių suvestinė','All metrics summary')}</h2><table><thead><tr><th>{t('Zona / rodiklis','Zone / metric')}</th><th>Min / Mean / Max</th><th>{t('Už ribų','Outside target')}</th><th>{t('Aprėptis','Coverage')}</th><th>Δ</th></tr></thead><tbody>{report.metrics.map(m=><tr key={`${m.sectionId}:${m.metric}`}><th>{m.name} · {metricLabel(m.metric)}</th><td>{number(m.minimum)} / {number(m.mean)} / {number(m.maximum)} {m.unit}</td><td>{number(m.outsideObservedPct)} %</td><td>{number(m.coveragePct)} %</td><td>{number(m.peerDelta)} {m.unit}</td></tr>)}</tbody></table></section>
      <footer className="diag-method"><strong>{t('Metodika ir patikimumas','Method and reliability')}</strong><p>{t('Matuojama: T, RH, CO₂, lux ir įdiegti papildomi sensoriai. Apskaičiuojama: oro VPD, laiku svertiniai vidurkiai ir skirtumai. Tarp matavimų reikšmė galioja ribotą laiką; likęs tarpas laikomas nežinomu.','Measured: T, RH, CO₂, lux and installed probes. Derived: air VPD, time-weighted means and differences. Readings are held for a bounded interval; remaining gaps are unknown.')}</p><p>{t('Zonų skirtumai lyginami sutampančiuose 5 min languose. Reitingui reikia bent 50 % aprėpties. Vienodumas ir tinkamumas augalui yra skirtingi rodikliai.','Peer differences use overlapping 5-minute windows. Ranking requires at least 50% coverage. Uniformity and crop suitability are separate metrics.')}</p><p>{t('Aprėpties vardiklis konservatyvus: kiekvienam stebėtam mazgo priskyrimui skiriamas visas laikotarpis. Perkėlus mazgą, senos ir naujos zonos aprėptis gali būti sumažinta. Kontekstas fiksuojamas gavus matavimą; pavėluotiems paketams ankstesnė konfigūracija neatkuriama.','Coverage uses the full window for every observed node assignment. Moving a node can reduce coverage in both zones. Context is captured on receipt; earlier configuration is not reconstructed for delayed packets.')}</p><small>{report.methodVersion} · {t('Sugeneruota','Generated')} {date(report.generatedAt)}</small></footer>
    </>:null}
  </div>
}
