import {metricDefinitions} from '../../domain/metricRegistry'
import type {DiagnosticReport} from './types'
import type {FindingGroup} from './findings'

export default function DiagnosticExplanation({report,group,lt}:{report:DiagnosticReport;group:FindingGroup;lt:boolean}){
 const t=(a:string,b:string)=>lt?a:b
 const n=(v:number|null)=>v==null?'—':v.toLocaleString(lt?'lt-LT':'en-GB',{maximumFractionDigits:1})
 const date=(v:string)=>new Date(v).toLocaleString(lt?'lt-LT':'en-GB',{timeZone:report.timeZone,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})
 const label=(m:string)=>{const def=metricDefinitions[m as keyof typeof metricDefinitions];return def?(lt?def.labelLt:def.label):m}
 const analyses=(report.explanations||[]).filter(e=>e.sectionId===group.sectionId&&group.items.some(i=>i.metric===e.metric)).sort((a,b)=>Object.values(b.directions).reduce((s,d)=>s+d.minutes,0)-Object.values(a.directions).reduce((s,d)=>s+d.minutes,0))
 if(!analyses.length)return <p>{t('Ši ataskaita išsaugota be išsamios įvykių analizės. Nežinomų trukmių ir priežasčių nepildome spėjimais.','This report has no detailed event analysis. Missing durations and causes are not inferred.')}</p>
 return <div className="diag-explanation">{analyses.map(a=>{
  const unit=group.items.find(i=>i.metric===a.metric)?.unit||''
  return <section key={`${a.nodeId}:${a.metric}`}><h3>{a.nodeName} · {label(a.metric)}</h3>
   {Object.entries(a.directions).map(([direction,d])=><div className="diag-diagnosis" key={direction}>
    <h4>{direction==='below'?t('Reikšmės žemiau nustatytos ribos','Readings below the configured target'):t('Reikšmės aukščiau nustatytos ribos','Readings above the configured target')}</h4>
    <dl><dt>{t('Kiek nukrypo?','How far outside target?')}</dt><dd>{t('Stipriausias nukrypimas','Largest excursion')}: <strong>{n(d.peak.value)} {unit}</strong>, {t('riba tuo metu','target at that time')} {n(d.peak.limit)} {unit}. {t('Skirtumas','Difference')}: {n(d.peak.departure)} {unit} ({date(d.peak.at)}).</dd>
    <dt>{t('Kiek laiko ir kaip dažnai?','How long and how often?')}</dt><dd>{n(d.minutes/60)} h · {d.eventCount} {t('atskirų epizodų','separate episodes')} · {d.days} {t('dienos','days')}. {t('Ilgiausias nenutrūkstamas epizodas','Longest continuous episode')}: {n(d.longestMinutes/60)} h. {t('Trukmė tik šiam jutikliui; duomenų tarpas nutraukia epizodą.','Duration applies only to this sensor; a data gap ends an episode.')}</dd>
    <dt>{t('Kuriuo paros metu?','At what time of day?')}</dt><dd>{t('Daugiausia nukrypimo laiko sukaupta','Most excursion time occurred at')}: {d.peakHours.map(h=>`${String(h.hour).padStart(2,'0')}:00–${String((h.hour+1)%24).padStart(2,'0')}:00 (${n(h.minutes/60)} h)`).join('; ')} · {report.timeZone}.</dd>
    <dt>{t('Tik čia ar ir kitur?','Only here or elsewhere too?')}</dt><dd>{d.scope==='insufficient-peers'?t('Stipriausio nukrypimo metu nepakako kitų jutiklių palyginimui.','Too few comparable sensors at the largest excursion.'):t(`Stipriausio nukrypimo metu ta pačia kryptimi už savo ribų buvo ${d.peersAtPeak.sameDirectionCount} iš ${d.peersAtPeak.configuredCount} palyginamų kitų jutiklių.`,`At the largest excursion, ${d.peersAtPeak.sameDirectionCount} of ${d.peersAtPeak.configuredCount} comparable other sensors were outside their own targets in the same direction.`)} {d.scope==='local'?t('Tai palaiko vietinio skirtumo hipotezę tuo momentu.','This supports a local difference at that moment.'):d.scope==='widespread'?t('Tai palaiko bendresnės klimato problemos hipotezę tuo momentu.','This supports a more widespread climate issue at that moment.') : ''}</dd></dl>
    {d.matchedRelated?.length?<div><h4>{t('Kitų rodiklių pokytis tuo pačiu paros metu','Other measurements at matching times of day')}</h4>{d.matchedRelated.map(r=><p key={r.metric}>{label(r.metric)}: {t('per šios krypties nukrypimus','during excursions in this direction')} <strong>{n(r.during)}</strong>, {t('tuo pačiu paros metu, kai pagrindinis rodiklis buvo ribose','at matching hours when the main metric was in target')} {n(r.baseline)} {metricDefinitions[r.metric as keyof typeof metricDefinitions]?.unit||''}. {t('Palyginta po','Matched')} {n(r.matchedMinutes/60)} h. {t('Sutapimas nepatvirtina priežasties.','Association does not establish cause.')}</p>)}</div>:null}
    <details><summary>{t('Ilgiausių epizodų laikai','Longest episode times')}</summary>{d.longestEvents.map(e=><p key={e.from}>{date(e.from)} → {date(e.to)} · {n(e.minutes/60)} h</p>)}</details>
    <p className="diag-reason"><strong>{t('Ką tikrinti ir kodėl.','What to check and why.')}</strong> {a.estimatedPct>0?t('Pirmiausia patvirtinkite, ar tuo laikotarpiu galiojo šios ribos. Dalis jų paimta iš vėlesnės konfigūracijos, todėl išvada gali keistis.','First confirm the targets for this period. Some come from later configuration, which may change the conclusion.'):d.scope==='local'?t('Kadangi kiti jutikliai tuo momentu tokio nukrypimo nerodė, pirmiausia patikrinkite šio jutiklio tikslumą ir vietines sąlygas. Nepradėkite nuo viso šiltnamio nustatymų keitimo.','Other sensors did not show this excursion at that moment. First verify this sensor and local conditions before changing greenhouse-wide settings.'):d.scope==='widespread'?t('Kadangi nukrypimą tuo momentu rodė dauguma palyginamų jutiklių, pirmiausia palyginkite bendrus klimato nustatymus ir įrangos įvykius su nurodytais laikais.','Most comparable sensors shared the excursion at that moment. First compare greenhouse-wide settings and equipment events with these times.'):t('Priežasties duomenys neatskiria. Patikrinkite ribų tinkamumą ir palyginkite šį jutiklį su kontroliniu matavimu.','The evidence does not distinguish the cause. Verify target suitability and compare this sensor with a reference reading.')}</p>
   </div>)}
   <h4>{t('Ar padėtis keičiasi?','Is it changing?')}</h4><p>{a.trend==='comparable'?t(`Pirmoje laikotarpio pusėje už ribų buvo ${n(a.halves[0].outsidePct)} %, antroje – ${n(a.halves[1].outsidePct)} % stebėto laiko. Tai laikotarpių palyginimas, ne įrodymas, kad pakeitimas sukėlė rezultatą.`,`Outside targets for ${n(a.halves[0].outsidePct)}% of observed time in the first half and ${n(a.halves[1].outsidePct)}% in the second. This comparison does not prove an intervention caused the change.`):t('Patikimam abiejų laikotarpio pusių palyginimui nepakanka aprėpties arba patvirtintų, vienodų istorinių ribų.','Insufficient coverage or consistent, verified historical targets for a reliable comparison of the two halves.')}</p>
   <p><strong>{t('Kaip patikrinti rezultatą.','How to verify the outcome.')}</strong> {t('Užregistruokite atliktą veiksmą. Po jo palyginkite tą patį jutiklį panašiu paros metu: nukrypimo dydį, trukmę ir kitų vietų rodmenis. Vien mažesnis vidurkis pagerėjimo nepatvirtina.','Record the intervention. Afterwards compare this sensor at similar times of day: excursion size, duration and readings elsewhere. A lower mean alone does not establish improvement.')}</p>
  </section>
 })}</div>
}
