import {metricDefinitions} from '../../domain/metricRegistry'
import type {DiagnosticReport,GrowthRisk} from './types'
import type {AgronomicAdvice} from './agronomicAdvice'
type Pair=[string,string]
type Rule={title:Pair;meaning:Pair;action:Pair;verify:Pair;source:keyof typeof sources;priority:number}
const sources={
 solution:{title:'Oklahoma State Extension · Solution temperature and oxygen',url:'https://extension.okstate.edu/fact-sheets/principles-of-small-scale-aquaponics'},
 heat:{title:'MSU Extension · Temperature and crop development',url:'https://www.canr.msu.edu/uploads/resources/pdfs/high-temperature.pdf'},
 roots:{title:'UMass Extension · Root function and growing conditions',url:'https://www.umass.edu/agriculture-food-environment/greenhouse-floriculture/fact-sheets/root-diseases-of-greenhouse-crops'},
 rootTemp:{title:'UMass Extension · Air and substrate temperature',url:'https://www.umass.edu/agriculture-food-environment/sites/ag.umass.edu/files/pdf-doc-ppt/handoutlight_temperature_relative_humidity_1_12_2016.pdf'},
 ec:{title:'UMass Extension · Interpreting EC',url:'https://www.umass.edu/agriculture-food-environment/greenhouse-floriculture/fact-sheets/soluble-salts-electrical-conductivity-ec-for-greenhouse-crops'},
 ph:{title:'University of Georgia Extension · pH and plant nutrition',url:'https://fieldreport.caes.uga.edu/publications/B1256/essential-ph-management-in-greenhouse-crops-ph-and-plant-nutrition/'},
 nutrition:{title:'UNH Extension · Nutrient problem diagnosis',url:'https://extension.unh.edu/resource/scouting-managing-greenhouse-nutrient-problems-fact-sheet'},
 co2:{title:'Oklahoma State Extension · Light and CO₂',url:'https://extension.okstate.edu/fact-sheets/greenhouse-carbon-dioxide-supplementation'},
 light:{title:'MSU Extension · Light quantity and photoperiod',url:'https://www.canr.msu.edu/uploads/resources/pdfs/lightquality.pdf'},
 water:{title:'MSU Extension · VPD and water balance',url:'https://www.canr.msu.edu/resources/vpd_vs_relative_humidity'},
}
const verifyClimate:Pair=['Po korekcijos palyginkite nukrypimo trukmę panašiu paros metu, lapų būklę ir gretimų vietų rodmenis.','After adjustment compare excursion duration at similar hours, leaf condition and nearby readings.']
const verifyRoot:Pair=['Kontroliniu metodu pakartokite šaknų zonos matavimą toje pačioje vietoje. Vertinkite ir šaknų būklę, ne tik jutiklio rodmenį.','Repeat a reference root-zone measurement at the same location. Assess roots as well as the sensor reading.']
const verifyNutrition:Pair=['Pakartokite pH ir EC tyrimą tuo pačiu metodu; stebėkite naujo augimo būklę. Vien rodmens sugrįžimas į ribas neįrodo, kad augalas atsigavo.','Repeat pH and EC tests using the same method; monitor new growth. A reading returning to target alone does not establish recovery.']
export const growthAdviceRules:Record<string,Rule>={
 'heat-load':{title:['Šilumos apkrova gali trikdyti augimą','Heat load may disrupt growth'],meaning:['Temperatūra virš kultūros profilio ribos gali keisti vystymosi tempą ir didinti kvėpavimo sąnaudas. Žydėjimo ar derėjimo pažeidimo iš oro temperatūros vienos nustatyti negalima.','Temperature above the crop profile may alter development and increase respiratory demand. Air temperature alone does not establish damage to flowering or fruiting.'],action:['Patikrinkite vėdinimo ir vėsinimo pajėgumą nukrypimo valandomis. Šešėliavimą didinkite tik įvertinę šviesos kiekį — sumažinus šilumą pernelyg stipriu šešėliu galima apriboti fotosintezę.','Check ventilation and cooling capacity during excursions. Assess available light before adding shade; excessive shading can restrict photosynthesis.'],verify:verifyClimate,source:'heat',priority:65},
 'cold-growth':{title:['Vėsa gali lėtinti vystymąsi ir keisti laistymo poreikį','Cool conditions may slow development and change irrigation needs'],meaning:['Žemesnė nei profilyje numatyta temperatūra gali lėtinti augimą. Įprastas laistymo ir auginimo darbų grafikas tuomet gali nebeatitikti faktinio augalo tempo.','Below-profile temperature can slow growth. Existing irrigation and crop scheduling may no longer match actual development.'],action:['Patikrinkite šildymo režimą ir temperatūrą augalų aukštyje. Prieš išlaikydami ankstesnį laistymo dažnį įvertinkite substrato džiūvimą; neskubinkite augimo vien papildomomis trąšomis.','Check heating and temperature at crop height. Assess substrate drying before retaining the previous irrigation frequency; extra fertilizer alone will not accelerate temperature-limited growth.'],verify:verifyClimate,source:'heat',priority:60},
 'root-cold':{title:['Šalta šaknų zona gali riboti įsisavinimą','Cold roots may restrict uptake'],meaning:['Kai šaknų zona vėsesnė nei numatyta profilyje, vandens ir maisto medžiagų įsisavinimas gali sulėtėti. Tai gali atrodyti kaip tręšimo problema.','A root zone colder than the profile target can slow water and nutrient uptake and resemble a nutrition problem.'],action:['Patikrinkite substrato temperatūrą kontroliniu zondu, suolių ar šaknų zonos šildymą. Tręšimo nedidinkite vien dėl lėto augimo — pirmiausia patikrinkite šaknų temperatūrą, pH ir EC.','Verify substrate temperature and bench or root-zone heating. Do not increase fertilizer solely for slow growth; check root temperature, pH and EC first.'],verify:verifyRoot,source:'rootTemp',priority:75},
 'root-hot':{title:['Per šilta šaknų zona gali bloginti šaknų veiklą','An overly warm root zone may impair root function'],meaning:['Šaknų temperatūra virš profilio ribos keičia jų kvėpavimą ir gali didinti deguonies poreikį. Matavimas pats savaime neparodo deguonies trūkumo ar puvinio.','Root temperature above the profile changes respiration and may increase oxygen demand. Temperature alone does not establish oxygen shortage or rot.'],action:['Patikrinkite karštus vamzdžius, tiesiogiai saulės kaitinamas talpas ir drenažą. Šaknų nevėsinkite nepatikrintu papildomu laistymu, jei substratas jau šlapias.','Inspect hot pipes, sun-heated containers and drainage. Do not use extra irrigation as cooling without checking whether the substrate is already wet.'],verify:verifyRoot,source:'roots',priority:70},
 'water-cold':{title:['Šaltas vanduo gali vėsinti šaknų zoną','Cold water may cool the root zone'],meaning:['Vandens temperatūra žemiau profilio ribos gali vėsinti šaknis laistymo metu; poveikį lemia tiekimo vieta, tūris ir substrato temperatūra.','Below-profile water temperature may cool roots during irrigation; the effect depends on delivery, volume and substrate temperature.'],action:['Pamatuokite temperatūrą ties augalu, ne tik rezervuare, ir palyginkite substratą prieš laistymą bei po jo. Koreguokite tiekimą tik patvirtinę šaknų atvėsimą.','Measure water at the plant, not only in the tank, and compare substrate temperature before and after irrigation. Adjust delivery if root cooling is confirmed.'],verify:verifyRoot,source:'rootTemp',priority:55},
 'water-hot':{title:['Šiltame tirpale verta tikrinti deguonies tiekimą','Warm solution warrants checking oxygen supply'],meaning:['Šiltame vandenyje deguonies tirpumas mažesnis. Hidroponikoje tai svarbu šaknims, tačiau temperatūros jutiklis neišmatuoja ištirpusio deguonies.','Oxygen solubility falls as water warms. This matters to hydroponic roots, but a temperature probe does not measure dissolved oxygen.'],action:['Jei matuojamas hidroponinis tirpalas, patikrinkite jo cirkuliaciją, aeraciją ir ištirpusį deguonį. Jei tai tik laistymo bakas, pirmiausia tikrinkite vandens temperatūrą ties augalais.','For hydroponic solution, check circulation, aeration and dissolved oxygen. For an irrigation tank, first check delivery temperature at the plants.'],verify:verifyRoot,source:'solution',priority:70},
 'dry-root':{title:['Šaknų zonos drėgmė gali riboti vandens tiekimą','Root-zone moisture may limit water supply'],meaning:['Drėgmė žemiau substratui nustatytos ribos rodo galimą vandens tiekimo ribojimą. Vienas zondas neparodo visos sekcijos drėgmės.','Moisture below the substrate target suggests possible water-supply limitation. One probe does not represent the entire section.'],action:['Patikrinkite lašintuvą ir drėgmę keliuose tos vietos gyliuose. Jei trūkumas patvirtinamas, koreguokite laistymo laiką ar dažnį ir patikrinkite paskirstymo vienodumą.','Check the emitter and moisture at several depths nearby. If a deficit is confirmed, adjust timing or frequency and verify distribution uniformity.'],verify:verifyRoot,source:'water',priority:75},
 'wet-root':{title:['Ilgai šlapias substratas gali riboti šaknų aeraciją','Persistently wet substrate may restrict root aeration'],meaning:['Drėgmė virš profilio ribos gali reikšti per lėtą džiūvimą. Užmirkimas mažina oro porų dalį, bet vien drėgmės rodmuo nepatvirtina šaknų ligos.','Above-profile moisture may indicate slow drying. Waterlogging reduces air-filled pores, but moisture alone does not diagnose root disease.'],action:['Prieš kitą laistymą patikrinkite drenažą, šaknų būklę ir kontrolinę substrato drėgmę. Vytimas šlapiame substrate nėra automatinė priežastis pilti daugiau vandens.','Before the next irrigation check drainage, roots and reference moisture. Wilting in wet substrate is not an automatic reason to add water.'],verify:verifyRoot,source:'roots',priority:80},
 'substrate-salinity':{title:['Druskų koncentracija gali apsunkinti vandens įsisavinimą','Salt concentration may hinder water uptake'],meaning:['Aukštas substrato EC rodo didesnę ištirpusių druskų koncentraciją. Augalas gali sunkiau pasisavinti vandenį net tada, kai substratas drėgnas.','High substrate EC indicates more dissolved salts. Water uptake can become harder even in moist substrate.'],action:['Patvirtinkite EC tinkamu substrato tyrimo metodu ir palyginkite su tiekiamo vandens bei tirpalo EC. Tikrinant drenažą nustatykite, ar reikia koreguoti koncentraciją, ar druskų kaupimąsi; nepradėkite nuo papildomų trąšų.','Confirm EC with an appropriate substrate test and compare input water and feed EC. Check drainage to distinguish concentrated feed from salt accumulation before changing fertilizer.'],verify:verifyNutrition,source:'ec',priority:80},
 'substrate-low-ec':{title:['Verta patikrinti maisto medžiagų pasiūlą šaknims','Check nutrient supply to the root zone'],meaning:['Mažas substrato EC gali rodyti mažą druskų koncentraciją, bet neatskleidžia konkretaus elemento trūkumo. Rodmenį veikia drėgmė ir tyrimo metodas.','Low substrate EC can indicate dilute salts but does not identify a particular nutrient deficiency. Moisture and testing method affect interpretation.'],action:['Patikrinkite pH, drėgmę ir trąšų tiekimą. Tręšimą didinkite tik patvirtinę trūkumą substrato ar augalų audinių tyrimu ir atsižvelgę į kultūros poreikį.','Check pH, moisture and feed delivery. Increase nutrition only after confirming insufficient supply with substrate or tissue testing against crop requirements.'],verify:verifyNutrition,source:'nutrition',priority:50},
 'solution-high-ec':{title:['Tiekiamas tirpalas gali būti per koncentruotas','Feed solution may be too concentrated'],meaning:['Tirpalo EC virš profilio ribos gali reikšti per koncentruotą tiekimą. Tai dar neįrodo, kad druskos susikaupė substrate.','Solution EC above target may indicate concentrated feed; it does not establish salt accumulation in the substrate.'],action:['Kontroliniu matuokliu patikrinkite tirpalą ir pradinį vandenį, dozatorių bei maišymo proporcijas. Atskirai pamatuokite substrato EC; nepainiokite skirtingų matavimo vietų ribų.','Verify solution and source-water EC, injector operation and mixing ratios. Measure substrate EC separately; targets from different sampling locations are not interchangeable.'],verify:verifyNutrition,source:'ec',priority:75},
 'solution-low-ec':{title:['Trąšų tiekimas gali neatitikti nustatytos koncentracijos','Feed delivery may be below the intended concentration'],meaning:['Mažas tirpalo EC gali reikšti praskiedimą ar tiekimo neatitikimą. Konkretus maisto medžiagos trūkumas iš EC nenustatomas.','Low solution EC can reflect dilution or a feed-delivery mismatch. EC cannot identify a specific nutrient deficiency.'],action:['Patikrinkite trąšų atsargas, dozatorių, pradinio vandens EC ir pH. Koncentraciją keiskite pagal kontrolinį matavimą ir kultūros profilį, ne vien pagal augalų spalvą.','Check fertilizer stock, injector, source-water EC and pH. Adjust concentration using a reference measurement and crop profile, not leaf colour alone.'],verify:verifyNutrition,source:'nutrition',priority:55},
 'ph-high':{title:['Maisto medžiagos gali būti sunkiau prieinamos, nors trąšų pakanka','Nutrients may be less available despite adequate fertilizer'],meaning:['Per aukštas pH gali mažinti kai kurių mikroelementų, įskaitant geležį, prieinamumą. Didesnė trąšų dozė nepašalina pH sukeltos prieigos problemos.','Excessive pH can reduce availability of micronutrients including iron. More fertilizer does not remove a pH-driven availability problem.'],action:['Patvirtinkite pH kalibruotu matuokliu, nustatykite, ar matuojamas tirpalas, ar substratas, ir patikrinkite vandens šarmingumą. Korekciją parinkite pagal kultūrą ir tyrimą, nespėdami rūgšties dozės.','Verify pH with a calibrated meter, identify solution versus substrate sampling and test water alkalinity. Choose a crop-specific correction from testing rather than guessing an acid dose.'],verify:verifyNutrition,source:'ph',priority:80},
 'ph-low':{title:['Per mažas pH gali išbalansuoti maisto medžiagų prieinamumą','Low pH may unbalance nutrient availability'],meaning:['Per mažas pH gali padidinti kai kurių mikroelementų prieinamumą iki nepageidaujamo lygio. Jautrumas priklauso nuo kultūros ir auginimo terpės.','Low pH can make some micronutrients excessively available. Sensitivity depends on the crop and growing medium.'],action:['Patikrinkite kalibravimą, mėginio vietą, vandens šarmingumą ir trąšų rūgštinantį poveikį. Pirmiausia nustatykite pH kritimo priežastį, o ne didinkite visų maisto medžiagų dozę.','Check calibration, sampling location, water alkalinity and fertilizer acidity. Establish why pH is falling before changing overall nutrient supply.'],verify:verifyNutrition,source:'ph',priority:80},
 'co2-low-lit':{title:['Šviesoje CO₂ gali riboti fotosintezę','CO₂ may limit photosynthesis during the light period'],meaning:['CO₂ žemiau profilio ribos tuo metu, kai užfiksuota šviesa, gali reikšti nepakankamą pasiūlą lapams. Silpna šviesa ar vandens stresas taip pat gali riboti atsaką į papildomą CO₂.','Below-target CO₂ during measured light may indicate limited supply to leaves. Low light or water stress can also limit response to enrichment.'],action:['Patikrinkite CO₂ matuoklį ir oro pasiskirstymą lajoje. Prieš didindami tiekimą įvertinkite šviesos kiekį, VPD ir vėdinimo būseną; papildymas atviromis angomis gali būti neefektyvus.','Check the CO₂ sensor and canopy air distribution. Assess light, VPD and ventilation before increasing supply; enrichment with open vents may be inefficient.'],verify:verifyClimate,source:'co2',priority:65},
 'co2-high-lit':{title:['CO₂ tiekimą verta suderinti su faktine šviesa','Match CO₂ supply to available light'],meaning:['CO₂ virš profilio ribos nereiškia proporcingai didesnės fotosintezės. Naudą lemia šviesa ir kitos augimo sąlygos.','Above-profile CO₂ does not imply proportionally greater photosynthesis. Light and other growing conditions determine the response.'],action:['Patikrinkite matuoklį, tiekimo valdymą ir faktinę šviesą. Jei papildymas vyksta, jo tikslą derinkite su kultūros režimu ir vėdinimu.','Check the sensor, supply controls and measured light. If enriching, align the target with the crop regime and ventilation.'],verify:verifyClimate,source:'co2',priority:45},
 'co2-high-dark':{title:['Tamsoje CO₂ papildymas gali neturėti fotosintetinės naudos','CO₂ enrichment in darkness may provide no photosynthetic benefit'],meaning:['CO₂ virš profilio ribos sutapo su užfiksuota tamsa. Didesnę koncentraciją gali lemti ir augalų ar substrato kvėpavimas, todėl tiekimo gedimas neįrodytas.','Above-profile CO₂ coincided with measured darkness. Plant or substrate respiration may also raise CO₂, so a supply fault is not established.'],action:['Patikrinkite, ar tuo metu iš tiesų veikė CO₂ tiekimas. Jei taip, peržiūrėkite jo susiejimą su apšvietimu ir vožtuvo sandarumą.','Check whether CO₂ supply actually operated then. If it did, review the lighting interlock and valve closure.'],verify:verifyClimate,source:'co2',priority:55},
 'light-low':{title:['Planuotu šviesos metu augalui gali trūkti energijos','Light may be insufficient during the planned light period'],meaning:['Apšvietimas žemiau profilio ribos gali riboti augimui gaunamą energiją. Vien trąšų ar CO₂ didinimas šviesos trūkumo neišsprendžia.','Below-profile light can restrict energy available for growth. Extra fertilizer or CO₂ alone does not resolve insufficient light.'],action:['Patikrinkite šviestuvus, užuolaidas, dangos švarą ir jutiklio padėtį lajos lygyje. Apšvietimo trukmę keiskite tik įvertinę kultūros fotoperiodą ir paros šviesos sumą.','Check lamps, screens, cover cleanliness and sensor position at canopy height. Change lighting duration only after checking crop photoperiod and daily light integral.'],verify:verifyClimate,source:'light',priority:65},
 'light-high':{title:['Didelę šviesos apkrovą reikia derinti su lapų vėsinimu','High light load needs adequate leaf cooling'],meaning:['Šviesa virš profilio ribos gali didinti lapų energinę apkrovą. Tai nepatvirtina nudegimo; reikšmę turi lapų temperatūra, vandens tiekimas ir kultūra.','Above-profile light can increase leaf energy load. It does not establish scorch; leaf temperature, water supply and crop sensitivity matter.'],action:['Prieš stipriau šešėliuodami pamatuokite lapų temperatūrą ir patikrinkite vandens tiekimą. Išsaugokite kultūrai reikalingą paros šviesos kiekį.','Check leaf temperature and water supply before adding substantial shade. Preserve the crop’s required daily light quantity.'],verify:verifyClimate,source:'light',priority:65},
 'light-at-night':{title:['Šviesa už numatyto grafiko gali keisti fotoperiodą','Light outside the schedule may alter photoperiod'],meaning:['Išmatuota šviesa numatytu tamsos metu gali trumpinti nepertraukiamą naktį. Poveikis žydėjimui priklauso nuo kultūros; tyčinis nakties pertraukimas gali būti teisingas režimas.','Measured light during scheduled darkness can shorten the uninterrupted night. Flowering effects depend on crop; intentional night interruption may be valid.'],action:['Patikrinkite laikmatį, grafiką ir šviesos nutekėjimą iš gretimų zonų. Suderinkite faktinį režimą su kultūros žydėjimo strategija.','Check timers, schedule and light spill from adjacent areas. Align the actual regime with the crop’s flowering strategy.'],verify:verifyClimate,source:'light',priority:60},
 'dry-saline-root':{title:['Sausas ir druskingas substratas kartu riboja vandens prieinamumą','Dry and saline substrate jointly restrict water availability'],meaning:['Maža substrato drėgmė ir aukštas jo EC užfiksuoti vienu metu. Galimą vandens deficitą stiprina druskų sukeltas osmosinis poveikis.','Low substrate moisture and high substrate EC occurred together. Osmotic effects of salts can compound water deficit.'],action:['Pirmiausia patikrinkite vandens paskirstymą, substrato EC kontroliniu metodu ir drenažą. Drėgmės atkūrimą bei koncentracijos korekciją planuokite kartu; papildomas koncentruotas tręšimas gali pabloginti padėtį.','Check water distribution, reference substrate EC and drainage first. Plan moisture restoration and concentration correction together; additional concentrated fertilizer may worsen conditions.'],verify:verifyNutrition,source:'ec',priority:100},
 'wet-cold-root':{title:['Šaltas, šlapias substratas gali būti įsisavinimo kliūtis','Cold, wet substrate may be an uptake bottleneck'],meaning:['Per drėgnas pagal profilį substratas sutapo su per žema šaknų temperatūra. Lėtas džiūvimas ir vėsios šaknys gali riboti įsisavinimą.','Above-target substrate moisture coincided with below-target root temperature. Slow drying and cold roots can restrict uptake.'],action:['Prieš papildomą laistymą ar tręšimą patikrinkite drenažą ir šaknų zonos šildymą. Kontroliniu matavimu patvirtinkite sąlygas prie šaknų.','Check drainage and root-zone heating before additional irrigation or fertilizer. Verify conditions near roots with a reference measurement.'],verify:verifyRoot,source:'rootTemp',priority:95},
 'ph-ec-imbalance':{title:['Mažą EC vertinkite kartu su netinkamu pH','Interpret low EC together with unsuitable pH'],meaning:['Mažas tirpalo EC sutapo su pH už profilio ribų. Vien didesnė trąšų koncentracija negarantuoja tinkamo maisto medžiagų prieinamumo.','Low solution EC coincided with pH outside the profile. Increasing feed concentration alone does not guarantee nutrient availability.'],action:['Patikrinkite abu matuoklius ir mėginio vietą. Pirmiausia nustatykite pH neatitikimo bei dozavimo priežastis, tada parinkite suderintą mitybos korekciją.','Verify both meters and sampling locations. Establish the pH and dosing causes before choosing a coordinated nutrition correction.'],verify:verifyNutrition,source:'nutrition',priority:95},
 'heat-light-mismatch':{title:['Šilumos ir šviesos režimai gali būti nesuderinti','Temperature and light may be mismatched'],meaning:['Aukšta temperatūra ir per silpna pagal profilį šviesa sutapo planuotu šviesos metu. Šiluma skatina procesus, kuriems gali trūkti šviesos suteikiamos energijos.','Above-profile temperature and below-profile light coincided in the planned light period. Temperature-driven processes may outpace available light energy.'],action:['Pirmiausia patikrinkite šešėliavimo ir apšvietimo būseną. Šildymo ar vėsinimo tikslą derinkite su faktine šviesa ir kultūros stadija; nesiūloma automatiškai pridėti trąšų.','Check shading and lighting first. Align heating or cooling targets with actual light and crop stage rather than automatically adding fertilizer.'],verify:verifyClimate,source:'heat',priority:90},
 'co2-water-limitation':{title:['Prieš CO₂ papildymą įvertinkite vandens stresą','Assess water stress before adding CO₂'],meaning:['Šviesoje mažas CO₂ sutapo su VPD virš profilio ribos. Jei augalas dėl vandens balanso užveria žioteles, papildomo CO₂ nauda gali būti ribota.','Low CO₂ in measured light coincided with above-profile VPD. If water imbalance closes stomata, extra CO₂ may have limited benefit.'],action:['Pirmiausia patikrinkite šaknų drėgmę ir augalų vandens būklę. Suderinkite vandens tiekimą bei mikroklimatą, tuomet vertinkite CO₂ tiekimo poreikį.','Check root moisture and plant water status first. Coordinate water supply and climate before assessing CO₂ enrichment needs.'],verify:verifyClimate,source:'water',priority:90},
}

export function growthAdvice(report:DiagnosticReport,lt:boolean):AgronomicAdvice[]{
 const t=(p:Pair)=>p[lt?0:1],n=(v:number)=>v.toLocaleString(lt?'lt-LT':'en-GB',{maximumFractionDigits:2})
 const all=(report.agronomy||[]).filter((r):r is GrowthRisk=>'primaryMetric' in r)
 const selected=new Map<string,GrowthRisk>()
 for(const r of all){const key=`${r.sectionId}:${r.kind}`;if(!selected.has(key)||selected.get(key)!.minutes<r.minutes)selected.set(key,r)}
 return [...selected.values()].filter(r=>growthAdviceRules[r.kind]).sort((a,b)=>growthAdviceRules[b.kind].priority-growthAdviceRules[a.kind].priority||b.minutes-a.minutes).map(r=>{
  const rule=growthAdviceRules[r.kind]
  const readings=r.support.map(s=>{const def=metricDefinitions[s.metric as keyof typeof metricDefinitions];return `${def?(lt?def.labelLt:def.label):s.metric}: ${n(s.minimum)}–${n(s.maximum)} ${s.unit}${s.target?` (${t(['profilis','profile'])} ${s.target.map(n).join('–')})`:''}`}).join('; ')
  const evidence=`${r.nodeName}: ${readings}. ${t(['Sąlyga užfiksuota','Condition recorded for'])} ${n(r.minutes/60)} h; ${t(['ilgiausiai be pertraukos','longest continuous period'])} ${n(r.longestMinutes/60)} h.`
  const context=[...r.crops,r.stage].filter(Boolean).join(' · ')
  let limits=context?`${t(['Auginimo kontekstas','Growing context'])}: ${context}. `:t(['Kultūra ar stadija nepatvirtinta; tai bendras fiziologinis vertinimas. ','Crop or stage is unconfirmed; this is a general physiological interpretation. '])
  if(r.estimated)limits+=t(['Istorinės ribos nepatvirtintos; prieš korekciją patikrinkite profilį. ','Historical targets are unverified; confirm the profile before adjustment. '])
  if(r.support.some(s=>s.metric==='lux'))limits+=t(['Liuksai yra apšviestumo indikatorius, ne augalui tenkančių fotonų ar DLI matavimas. ','Lux is an illuminance indicator, not a measurement of plant photons or DLI. '])
  if(['ph','ec','soilEc','soilMoisture','soilTemp','waterTemp'].includes(r.primaryMetric))limits+=t(['Išvada taikoma zondo vietai; tyrimo metodas ir terpė turi atitikti pasirinktas ribas. ','This applies at the probe location; sampling method and medium must match the configured limits. '])
  return {priority:rule.priority,id:`${r.sectionId}:${r.kind}`,place:r.sectionName,title:t(rule.title),meaning:t(rule.meaning),action:t(rule.action),verify:t(rule.verify),evidence,limits,source:sources[rule.source]}
 })
}
